name: projectdojo
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.1.0
  firebase_auth: ^1.1.3
  country_code_picker: ^2.0.1
  lottie: 
  pinput: 
  cloud_firestore:
  image_picker:
  firebase_storage:
  intl:
  local_auth:
  flutter_secure_storage:
  shimmer:
  google_fonts:
 
  curved_navigation_bar:
  provider:
  shared_preferences:
 
  animations:
  fl_chart:
  font_awesome_flutter:
  get:
  dio:
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:

flutter_icons:
  android: true
  ios: true
  image_path: "assets/appstore.png"
  adaptive_icon_background: "#191919"
  adaptive_icon_foreground: "assets/appstore.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/bottomleft.png
    - assets/bottomright.png
    - assets/revolutvault.png
    - assets/hoteli.jpg
    
    
    - assets/contact.json
    - assets/fofoerror.json
    - assets/phoneverify.json
    - assets/otpver.json
    - assets/mbesha.json
    - assets/id.json
    - assets/utambuzi.json
    - assets/growth.json
    - assets/signup.json
    - assets/pasiwadi.json
    - assets/onboardone.json
    - assets/onboardsecurity.json
    - assets/onboardsavings.json
    - assets/homeicon.json
    - assets/graph.json
    - assets/plus.json
    - assets/save.json
    - assets/profile.json
    - assets/firstleaf.json
    - assets/segundaleaf.json
    - assets/showscreen.json
    - assets/centology.json
    - assets/grupo.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  #"family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Trueno
      fonts:
        - asset: fonts/TruenoExBd.otf
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf
        - asset: fonts/Lato-Bold.ttf
          weight: 700
    - family: Anton
      fonts:
        - asset: fonts/Anton-Regular.ttf
       
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
